print('-' * 35)
print('Tugas 1 SISOP Kelas-A')
print('-' * 35)
print('Nama : Imelda Widya Ningrum')
print('NPM : 21083010052')
print('-' * 35)
print'notes: ')
print('Halo dunia!')
print('Ini adalah skrip Bash pertamaku di Linux!')
